config/routes.rb
Rails.application.routes.draw do
  get 'bugs/index'
  root 'bugs#index'
  resources :users
  resources :bugs

end

app/models/bug.rb
class Bug < ActiveRecord::Base
  belongs_to :user
  validates :title, :description, :issue_type, :priority, :status, presence: true
  validates :title, length: {minimum: 5, maximum: 80}
  validates :description, length: {minimum: 20, maximum: 800}

  enum issue_type: [:issue, :enhancement, :feature] 
  enum priority: [:low, :medium, :high]
  enum status: [:open, :closed, :monitor]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :bugs
  validates :fname, :lname, :email, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 105},
    uniqueness: { case_sensitive: false },
    format: { with: VALID_EMAIL_REGEX }
  validates :thumbnail, allow_blank: true, format: {with:
    %r{\.(gif|jpg|png)\Z}i,
    message: 'must be a URL for GIF, JPG or PNG image.'}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :all_bugs, only:[:index, :create, :destroy, :update]
  before_action :set_bug, only: [:show, :edit, :update, :destroy]
  before_action :set_statuses, :set_issue_types, :set_priorities
  respond_to :html, :js 

  # GET /bugs
  # GET /bugs.json
  def index
    @bugs = Bug.all
  end

  def all_bugs
    @bugs = Bug.all
  end

  # GET /bugs/1
  # GET /bugs/1.json
  def show
  end

  # GET /bugs/new
  def new
    @bug = Bug.new
  end

  # GET /bugs/1/edit
  def edit
  end

  # POST /bugs
  # POST /bugs.json
  def create
    @bug = Bug.new(bug_params)
    user = User.find(bug_params[:user_id])
    @bug.build_user(:id => user.id)
    @bug.save!
    @current_bug = @bug
    @bugs = Bug.all
  end

  


  # PATCH/PUT /bugs/1
  # PATCH/PUT /bugs/1.json
  def update
    @bug.update!(bug_params)
  end

  # DELETE /bugs/1
  # DELETE /bugs/1.json
  def destroy
    @bug.destroy!
  end

  def set_statuses
    @statuses = Bug.statuses
  end

  def set_priorities
    @priorities = Bug.priorities
  end

  def set_issue_types
    @issue_types = Bug.issue_types
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bug
      @bug = Bug.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bug_params
      params.require(:bug).permit(:title, :description, :issue_type, :priority, :status, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:fname, :lname, :email, :thumbnail)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bugs/_bug.html.erb
<% if bug == @current_bug %>
  <tr id="current_bug" class="bug">
<% else %>
  <tr class="bug">
<% end %>
  <td>
    <div class="bug_title"> <%= bug.title %> </div>
      <div class="bug_info">
        <span class="date"> <%= bug.updated_at.to_formatted_s(:long_ordinal)
        %> </span>
        <span class="user"> Reported by <%= (bug.user.try(:fname) || "NA") + " " + (bug.user.try(:lname) || "") %> 
        </span>
      </div>
      <div class="bug_text"> <%= bug.description %> </div>
    </div>
  </td>
  <td>
    <span class="type"> <%= bug.issue_type %>  </span>
  </td>
  <td>
    <span class="priority"> <%= bug.priority %>  </span>
  </td>
  <td>
    <span class="status"> <%= bug.status %>  </span>
  </td>
  <td>
    <span class="status actions"> <%= link_to 'Show', bug %>  </span>
  </td>
  <td>
    <span class="status actions"> <%= link_to 'Edit', edit_bug_path(bug), remote: true %>  </span>
  </td>
  <td>
    <span class="status actions"> <%= link_to 'Destroy', bug, method: :delete, data: { confirm: 'Are you sure?' }, remote: true %>  </span>
  </td>
</tr>

app/views/bugs/_form.html.erb
<%= form_for(@bug, remote: true) do |f| %>
  <% if @bug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bug.errors.count, "error") %> prohibited this bug from being saved:</h2>

      <ul>
      <% @bug.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.select :user_id,
    options_for_select(User.all.collect {|u| ["#{u.lname},
    #{u.fname}", u.id]},
    selected: (@bug.user ? @bug.user.id : User.first.id || '')),
    {} %>
    <%= link_to 'New User', new_user_path %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, size: "40x20" %>
  </div>
  <div class="field">
    <%= f.label :issue_type %><br>
    <%= f.select :issue_type, options_for_select(@issue_types.collect {|s| [s[0].humanize, s[0]]}, selected: @bug.issue_type), {} %>
  </div>
  <div class="field">
    <%= f.label :priority %><br>
    <%= f.select :priority, options_for_select(@priorities.collect {|s| [s[0].humanize, s[0]]}, selected: @bug.priority), {} %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.select :status, options_for_select(@statuses.collect {|s| [s[0].humanize, s[0]]}, selected: @bug.status), {} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bugs/create.js.erb
$('#bugs').empty()
$('#bugs').html("<%= j (render @bugs) %>");
$('#bug-form').slideUp(350);
$('#current_bug:nth-child(odd)').css({'background-color' : '#88ff88'}).animate({'background-color': '#CCCCCC'}, 1000);
$('#current_bug:nth-child(even)').css({'background-color' : '#88ff88'}).animate({'background-color': '#EFEFEF'}, 1000);

app/views/bugs/destroy.js.erb
$('#bugs').empty().html("<%= j (render @bugs) %>");

app/views/bugs/edit.html.erb
<h1>Editing Bug</h1>

<%= render 'form' %>

<%= link_to 'Show', @bug %> |
<%= link_to 'Back', bugs_path %>

app/views/bugs/edit.js.erb
$('#bug-form').empty().html("<%= j (render 'form') %>");
$('#bug-form').slideDown(350);

app/views/bugs/index.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<h1>Bugs</h1>
<table>
  <thead>
    <tr class="header">
      <th>Title</th>
      <th>Issue Type</th>
      <th>Priority</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody id="bugs">
    <%= render @bugs %>
  </tbody>
</table>

<span class="btn">
  <%= link_to 'New Bug', new_bug_path, remote: true  %>
</span>

<div id="bug-form" style="display:none;"></div>

app/views/bugs/new.html.erb
<h1>New Bug</h1>

<%= render 'form' %>

app/views/bugs/new.js.erb
$('#bug-form').html("<%= j (render 'form') %>");
$('#bug-form').slideDown(350);
if((obj = document.getElementById("submitbutton")) && obj != null){
  window.scrollTo(0, obj.offsetTop);
}

app/views/bugs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @bug.title %>
</p>

<p>
  <strong>User:</strong>
  <%= (@bug.user.try(:fname) || "NA") + " " + (@bug.user.try(:lname) || "")%>
</p>

<p>
  <strong>Description:</strong>
  <%= @bug.description %>
</p>

<p>
  <strong>Issue type:</strong>
  <%= @bug.issue_type %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @bug.priority %>
</p>

<p>
  <strong>Status:</strong>
  <%= @bug.status %>
</p>

<%= link_to 'Edit', edit_bug_path(@bug) %> |
<%= link_to 'Back', bugs_path %>

app/views/bugs/update.js.erb
$('#bugs').empty().html("<%= j (render @bugs) %>");
$('#bug-form').slideUp(350);

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Don't Bug Me</title>
  <%= stylesheet_link_tag 'application', media: 'all',
  'data-turbolinks-track'=> true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true%>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %>">
  <div id="banner">
    <%= image_tag("dilbert_bug.jpg") %>
    <%= @page_title || "Don't Bug Me" %>
  </div>
  <div id="columns">
    <div id="side">
      <ul>
        <li><a href="/">Home</a></li>
        <li><a href="/users">Users</a></li>
        <li><a href="/bugs">Bugs</a></li>
        <li><a href="/contact">Contact</a></li>
      </ul>
    </div>
    <div id="main">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'First Name' %><br>
    <%= f.text_field :fname %>
  </div>
  <div class="field">
    <%= f.label 'Last Name' %><br>
    <%= f.text_field :lname %>
  </div>
  <div class="field">
    <%= f.label 'Email' %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label 'Thumbnail' %><br>
    <%= f.text_field :thumbnail %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Thumbnail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.fname %></td>
        <td><%= user.lname %></td>
        <td><%= user.email %></td>
        <td><%= user.thumbnail %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First Name:</strong>
  <%= @user.fname %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @user.lname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Thumbnail:</strong>
  <%= @user.thumbnail %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'New Bug', new_bug_path %> |
<%= link_to 'Back', users_path %>